---
title: "Experience"
description: |
  My professional experiences, displayed in a professional format. 
output: 
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Professional

### [Yext](https://www.yext.com/)

I interned at Yext as a Technical Engagement Management Intern. As an intern, I led kickoff calls with clients, assisted with project management on implementation of Yext products (including as lead project manager for two clients), and coded R/Python scripts to assist Yext sales and management staff in data entry/processing tasks. Some live projects I've worked on/assisted with include the [Booz Allen Hamilton site searcher](https://www.boozallen.com/search-results.html?query=Booz+Allen&referrerPageUrl=https%3A%2F%2Fwww.boozallen.com%2F) and [Organic Krush site SEO](https://organickrush.com/). 

### [Research Assistant](https://www.princeton.edu/news/2021/11/18/datax-funding-new-ai-research-projects-princeton-across-disciplines)

I am a research assistant for Prof. Matias Iarcyzower, focusing on building AI/ML models alongside game theory to examine the interplay of money and politics. 

### [Texas Office of the Attorney General](https://www.texasattorneygeneral.gov/consumer-protection)

I worked at the Texas Attorney General's office as part of its nonpartisan Consumer Protection Division. There, I published privileged research and reports involving advertising technology and consumer data protection. To this end, I compiled, interpreted, and presented technical codebases, documentations, and expert statements/depositions on behalf of a lay audience of assistant attorneys general regarding ongoing confidential litigation in the tech industry. Specific issues I worked on include cryptography, protected categories in unsupervised clustering, privacy-utility optimization, and data protection in machine learning. 

As a final project, I collaborated with 4 other interns from the Attorney General's offices of Iowa and DC to present on US privacy standards to a nationwide coalition of Attorney General's offices, with representatives from all 50 states. 

### [IssueVoter](https://issuevoter.org/)

I previously worked at IssueVoter as a Business Development Intern, where I managed IssueVoter's CRM platform on Airtable and helped launch its civic engagement workshop series. I also authored several bill summaries, direct pieces of content launched on the IssueVoter website. 

# Teaching

I am currently an Undergraduate Course Assistant for Princeton's Department of Economics, where I TA for ECO310 - [Microeconomic Theory: A Mathematical Approach](https://registrar.princeton.edu/course-offerings/course-details?term=1222&courseid=001391) under Professor Can Urgun. I am also an R Programming consultant for the McGraw Center for Teaching and Learning. 

I was previously a course tutor for Princeton University courses through McGraw. I tutored for MAT175 - [Mathematics for Economics/Life Sciences](https://registrar.princeton.edu/course-offerings/course-details?term=1214&courseid=012060) and 
POL345 - [Introduction to Quantitative Social Science](https://registrar.princeton.edu/course-offerings/course-details?term=1214&courseid=013781).

